# Generated by Django 5.0.3 on 2024-07-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
