# Generated by Django 5.0.7 on 2024-07-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_postimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Image',
        ),
    ]
