# Generated by Django 5.0.7 on 2024-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
