# Generated by Django 5.0.7 on 2024-07-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_modify_date_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='writer',
        ),
    ]
