# Generated by Django 5.0.7 on 2024-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
