# Generated by Django 5.0.7 on 2024-07-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
